version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_desafio
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SeuPass#Seguro123
      - MSSQL_PID=Developer
    ports: [ "1433:1433" ]
    volumes: [ "sql_dados:/var/opt/mssql" ]
volumes:
  sql_dados:
